segmentio/analytics-go

- analytics.go
If no messages are passed to Client.send(), then skip the message call altogether.
Wasn't sure how to test this. /cc @tj
> Client.send() should not attempt to make an API if no messages

- analytics.go
Example which is not working for now:
```
client.Interval = 5 * time.Second
client.Size = 51
client.Verbose = true
for i := 0; i < 50; i++ {
client.Track(&analytics.Track{
Event:  "TestKeeen2",
UserId: "125",
Properties: map[string]interface{}{
"application": "Segment Desktop",
"version":     "1.1.0",
"platform":    "osx",
},
})
println(i)
}
println("flushing")
client.Close()
```
Before that fix, when ``Close()`` method is call, only a few messages are sending to Segment.io. That is happening because these messages was added in c.msgs channel but ``loop()`` didn't had enough time to process and add it in ``var msgs []interface{}``
> Fix: Close() method to wait until all messages was queued and sent

- analytics.go
This reverts #28 and a subsequent fix.
The issue was with this LOC. Once in a while (and likely more often than
not) it would read the same value it sends and exit, instead of
correctly waiting for the flush goroutine to clean up.
```
c.quit <- true
<-c.quit
close(c.msgs)
```
The 2nd commit fixed the #28 implementation, which was incorrectly
appending an array to an array.
```
msgs = append(msgs, c.drain(c.msgs))
```
This is a combination of 3 commits.
Revert "Append as elements instead of array."
This reverts commit 93892c42c4a95031cda1ed95e796e9f00ff49a44.
Revert "Close msgs after quite is done"
This reverts commit 76b1d6601a237934b023c2941ea55b9ae67d151d.
Revert "Fixed Close method to wait until all msgs was queued"
This reverts commit 4c6a6aecf6eac300f19443ac1aa074f571950c74.
> Revert #28

- analytics.go
It's tricky to deserialize HTTP errors since they're not guaranteed
to be in a consistent format.
e.g. failure to publish to NSQ returns "Internal Server Error" instead
of a JSON response.
Alternatively, an error message could be served from the load balancer,
NGINX, etc, in which case it most certainly won't be in the same format
as our API.
Additionally, we don't really need to deserialize the errors, since we
don't take any special action.
Simply reading the response and surfacing the raw body along with the
status and status code should be good enough for our purpose.
> Don't deserialize errors

- analytics.go
Stop the ticker to release associated resources as per the documentation (https://golang.org/pkg/time/#Ticker.Stop)
> Fixed resource leak with ticker

- Makefile
- analytics.go
- circle.yml
Makefile: Enable race detector, fix phony targets.
Circle: Clone the repo into our Gopath so circle doesn't fetch master
but actually uses the code in commit.
Go Vet fixes:
1. rename log to logf so go vet isn't confused
2. use %d for response.StatusCode instead of %s
> Update Circle Config

- .gitignore
- Godeps/Godeps.json
- analytics.go
- analytics_test.go
- circle.yml
- logger.go
- logger_test.go
@f2prateek 
@calvinfo 
Fixes #54 
These changes add the `analytics.Logger` interface to make it easier to plug any logger to instances of `analytics.Client`.
Please take a look and let me know if anything should be changed.
> add analytics.Logger interface + .gitignore

- analytics.go
@f2prateek 
Following up on our conversation, this should limit the number of goroutines spawned by the client and block if too many are in use already.
> limit the number of goroutines

- analytics.go
- error.go
- executor.go
- executor_test.go
@f2prateek 
Following up on our conversation and the changes we've made for 2.1.1, this adds the executor concept to limit the number of goroutines being executed.
This is mostly just a cleanup / testable version of what's in 2.1.1, but it calls the failure callback if the executor is full instead of blocking.
Please take a look and let me know if you're OK with the changes!
> add executor to limit the number of goroutines

- analytics.go
- analytics_test.go
- config.go
- context_test.go
- error_test.go
- fixtures/test-context-track.json
- fixtures/test-enqueue-alias.json
- fixtures/test-enqueue-group.json
- fixtures/test-enqueue-identify.json
- fixtures/test-enqueue-page.json
- fixtures/test-enqueue-screen.json
- fixtures/test-enqueue-track.json
- fixtures/test-integrations-track.json
- fixtures/test-interval-track.json
- fixtures/test-many-track.json
- fixtures/test-messageid-track.json
- fixtures/test-timestamp-track.json
- integrations_test.go
- json_test.go
- message.go
- properties.go
- properties_test.go
- traits_test.go
@f2prateek 
This PR adds 100% test coverage for the analytics package:
```
$ go test -cover     
PASS
coverage: 100.0% of statements
ok  	github.com/segmentio/analytics-go	0.202s
```
Going through this process allowed me to find a couple bugs, so it was definitely worth it (one bad key set on Properties, and failure callbacks not being called due to errors being dropped).
This should give us a good base to evolve the package in the future, as well as more confidence when time comes to make this release.
Please take a look and let me know if you see something that should be changed.
> 100% test coverage

- analytics.go
@f2prateek 
Adds a 10 second timeout on HTTP requests as a safety measure, we can figure out a better logic to set this value in the future.
> add HTTP timeout

- analytics_test.go
@f2prateek 
There were issues with Go 1.5 (which Circle-CI is using apparently, despite them saying they're on 1.6), the test HTTP transport did not implement `CancelRequest` which made the HTTP client refuse to send requests after the timeout was set.
> fix http timeout tests

- analytics.go
- timeout_15.go
- timeout_16.go
Use conditional compilation to set default timeout on http client.
For go 1.6+ we always the http timeout.
For other older versions, we set the timeout only if the transport
supports it.
cc @achille-roussel 
Closes #105
> Set default http timeout conditionally.

- context.go
Adding "DevinceInfo.AdvertisingID" since it is required in order to send
Server-to-Server events to AppsFlyer according to Segment documentation:
https://segment.com/docs/integrations/appsflyer/#server-side-tracking
> Adding "DevinceInfo.AdvertisingID" in order to send data to AppsFlyer integration

- context.go
Adding `Context.App.Namespace` since it is required in order to send Server-to-Server events to AppsFlyer.
This already exists in the Segment iOS SDK:
https://github.com/segmentio/analytics-ios/blob/27e8a7ff9548d74a985c9a16696c41a8115a6202/Analytics/Classes/Internal/SEGSegmentIntegration.m#L154
Segment's own server code for the AppsFlyer-integration according to @TeresaNesteby 
```lang=go
if (deviceType === 'ios') {
if (device.advertisingId) payload.idfa = device.advertisingId.toString()
payload.bundle_id = track.proxy('context.app.namespace')
} else if (device.advertisingId) {
payload.advertising_id = device.advertisingId.toString()
}
```
Segment ticket: 86810
> Adding `Context.App.Namespace` since it is required in order to send Server-to-Server events to AppsFlyer.

- analytics.go
This prompts users to upgrade to v3 of the library when they initialize the v2 version of the library.
It links them directly to the migration docs at https://segment.com/docs/sources/server/go/#migrating-from-v2
Ref: LIB-287
> Add deprecation log

- Makefile
- cmd/cli/main.go
This integrates the testing harness with the Go library. The harness invokes the cli package with fixtures and verifies that the library was able to send those messages to a webhook connected to the project succesfully.
https://paper.dropbox.com/doc/Libraries-End-to-End-Testing-Harness-dnotyIVIGYR7lnO1LcZtM
2 main additions:
1. A new CLI that conforms to our testing harness contract. https://paper.dropbox.com/doc/Libraries-End-to-End-Testing-Harness-dnotyIVIGYR7lnO1LcZtM#:uid=457845578223014078216812&h2=Contract. This allows the testing harness to test the Go library.
2. Run the harness on CI.
> Add End to End tests.

- vendor/github.com/segmentio/backo-go/.gitmodules
- vendor/github.com/segmentio/backo-go/README.md
- vendor/github.com/segmentio/backo-go/backo.go
- vendor/github.com/xtgo/uuid/AUTHORS
- vendor/github.com/xtgo/uuid/LICENSE
- vendor/github.com/xtgo/uuid/uuid.go
Dominic reported an issue when running go get on the v3 branch.
```
go get -u gopkg.in/segmentio/analytics-go.v3
package gopkg.in/segmentio/analytics-go.v3/vendor/github.com/segmentio/backo-go: gopkg.in/segmentio/analytics-go.v3 is a custom import path for https://gopkg.in/segmentio/analytics-go.v3, but /home/dominic/dev/src/gopkg.in/segmentio/analytics-go.v3/vendor/github.com/segmentio/backo-go is checked out from https://github.com/segmentio/backo-go
package gopkg.in/segmentio/analytics-go.v3/vendor/github.com/xtgo/uuid: gopkg.in/segmentio/analytics-go.v3 is a custom import path for https://gopkg.in/segmentio/analytics-go.v3, but /home/dominic/dev/src/gopkg.in/segmentio/analytics-go.v3/vendor/github.com/xtgo/uuid is checked out from https://github.com/xtgo/uuid
```
Nick pointed out that …
> fix vendored packages

- message.go
This patch raises the maxMessageBytes allowed per call to 32KB as stated
in documentation for V3.
> There is a maximum of 500KB per batch request and 32KB per call.
— [segment.com/docs/sources/server/go/#batching](https://segment.com/docs/sources/server/go/#batching)
Closes https://github.com/segmentio/analytics-go/issues/140.
> message: update maxMessageBytes to 32KB

- analytics.go
- analytics_test.go
Because of the way we construct messages with type assertion, custom types that satisfy the `Message` interface cannot be used.
Normally these would be silently dropped, but this returns an error so that failure is more obvious.
> return error if a custom type is enqueued

- alias.go
- alias_test.go
- analytics.go
- analytics_test.go
- group.go
- group_test.go
- identify.go
- identify_test.go
- message.go
- page.go
- page_test.go
- screen.go
- screen_test.go
- track.go
- track_test.go
By exposing the Message interfaces validate() method it allows the
analytics types to be used externally in other code and not confined to
the analytics-go library.
> Expose the Message interface Validate method
