segmentio/analytics-go

- analytics.go
- analytics_test.go
> Allow custom timestamps

- analytics.go
- analytics_test.go
Adds a second channel so that the background go-routine can indicate
when it finishes uploading events.
Also adds a test for the close method (not for the exact issue, since simply verifies that close flushes the queue).
Behaviour:
* Main goroutine sends a message on the `quit` channel
* Main goroutine closes the `msgs` channel so no more values can be sent
* Main goroutine waits on the `shutdown` channel
* Background goroutine gets the message on the `quit` channel
* Background goroutine drains the `msgs` channel
* Background goroutine uploads messages
* Background goroutine sends a message on the `shutdown` channel
* Main goroutine exits
> Clean shutdown

- analytics.go
- analytics_test.go
@f2prateek I have added `Integrations` to each struct rather than `Message` to be consistent with `Context`.
Also, kept it out of `Alias` because `Context` is skipped too, although both can be sent in `alias` messages.
> Add Integrations field

- analytics.go
By deferring starting the background loop goroutine, we allow clients to
set an arbitrary flush interval. Previously it would be ignored.
Note: The flush interval can only be configured before any messages are
enqueued.
Closes #36
> Defer starting loop.

- analytics.go
- analytics_test.go
> Set message ID only if not present

- analytics_test.go
I messed up and made the pull request from master initially, didn't find a way to change it so I'm making a new pull request for that.
Sorry for the noise.
Original PR: #63
> follow up of #63

- analytics.go
- analytics_test.go
- circle.yml
@f2prateek 
@calvinfo 
Fixes #55 
Follow up of #62 but will merge into `v3.0` instead of `master`.
Please let me know if anything needs to be changed.
> Close client twice (v3.0)

- analytics.go
@f2prateek 
Fixes #46 
Fixes #57 
Simple changes related to the two issues mentioned above, please let me know if you want to see something changed.
> use http.RoundTripper instead of http.Client

- screen.go
- screen_test.go
@f2prateek 
Quick fix for #76, simple copy/paste of the page.go and page_test.go files.
Let me know if anything should be changed.
> add screen type

- analytics.go
This addresses issue #72 by calling send async, and maintaining an inflight counter and introducing a new error logging case in the main select.
Let me know what you think.
Fixes #72
> Reduce blocking when sending

- analytics.go
- analytics_test.go
> fixing close

- analytics.go
- config.go
- message.go
@f2prateek 
Fixes #83 
Adds the Callback interface to notify the application of message sends success and failure.
> add analytics.Callback

- analytics.go
@f2prateek 
Pull changes from #50 to send requests asynchronously as described in #84
> async send

- context.go
- group.go
- identify.go
- traits.go
@f2prateek
This adds a Traits type in the style of what's done in the Java library, basically a map with a couple of helper methods to set the common fields.
Please take a look and let me know if something should be changed.
PS: I think we should add Integration and Properties types as well, even if there are no helper methods yet for these, at least that let us plan for upcoming release and we won't have to make API breaking changes, what do you think about it?
> add Traits type

- analytics.go
- config.go
- error.go
- message.go
- message_test.go
@f2prateek 
Changes related to limiting message batches to 500KB as described in #84
> limit message batches by size of serialized payload

- alias.go
- analytics_test.go
- group.go
- identify.go
- integrations.go
- page.go
- screen.go
- track.go
- traits.go
@f2prateek 
Follow up of #91, add the `Integrations` type which defines helper functions to turn on/off integrations.
> add Integrations type

- message.go
> define callback policy

- .gitignore
- Makefile
- analytics_test.go
- circle.yml
@f2prateek 
This PR adds detailed code coverage reports in the Circle-CI artifacts so we can keep a trace of the package's health.
> add code coverage artifacts

- Makefile
(changes described in https://github.com/segmentio/library-e2e-tester/releases/tag/0.2.0)
> update for new version of end to end testing tool

- analytics.go
- analytics_test.go
Trying to fix this issue https://github.com/segmentio/analytics-go/issues/145 in a way that @f2prateek suggested here https://github.com/segmentio/analytics-go/pull/138/
> Handle pointer types in Enqueue()

- Readme.md
Makes some small changes to improve the warning at the top of the file
> readme clarity 
